modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "enchantlib"
version = "${version}"
displayName = "enchantlib"
authors = "Astrum Void"
description = '''
Allows you to customize the enchantment table while also making chiseled bookshelves better.
'''
logoFile = "assets/enchantlib/icon.png"

[[dependencies.enchantlib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantlib]]
modId = "minecraft"
type = "required"
versionRange = "[>=1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantlib]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.enchantlib]]
modId = "midnightlib"
type = "required"
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "enchantlib.mixins.json"
