modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Mozilla Public License 2.0"

[[mods]]
modId = "enchantlib"
version = "${version}"
displayName = "enchantlib"
authors = "VoidTyron"
description = '''

'''
#logoFile = ""

[[dependencies.enchantlib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantlib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.enchantlib]]
modId = "midnightlib"
type = "required"
versionRange = "[1.6.9,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "enchantlib.mixins.json"
